package app.core.domain.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Compound key for a UserContextVar object.
 * <p>
 * The key of a UserContextVar is a User id and a ContextVarType id,
 * hence the fields of this class.
 */
@Embeddable
@SuppressWarnings(value="serial")
public class UserContextVarId implements java.io.Serializable {

    private Long userId;
    private Long contextVarTypeId;

    /** default constructor */
    public UserContextVarId() {
    }

    // Property accessors

    public UserContextVarId(Long userId, Long contextVarTypeId) {
    	this.userId = userId;
    	this.contextVarTypeId = contextVarTypeId;
	}

	/** Get the id of the User object. */
    @Column(name = "USER_ID")
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /** Get the id of the ContextVarType object. */
    @Column(name = "CONTEXT_VAR_TYPE_ID")
    public Long getContextVarTypeId() {
        return this.contextVarTypeId;
    }

    public void setContextVarTypeId(Long contextVarTypeId) {
        this.contextVarTypeId = contextVarTypeId;
    }

    /**
     * Auto-generated by hibernate tools.
     */
    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserContextVarId))
            return false;
        UserContextVarId castOther = (UserContextVarId) other;

        return ((this.getUserId() == castOther.getUserId()) || (this
                .getUserId() != null
                && castOther.getUserId() != null && this.getUserId().equals(
                castOther.getUserId())))
                && ((this.getContextVarTypeId() == castOther
                        .getContextVarTypeId()) || (this.getContextVarTypeId() != null
                        && castOther.getContextVarTypeId() != null && this
                        .getContextVarTypeId().equals(
                                castOther.getContextVarTypeId())));
    }

    /**
     * Auto-generated by hibernate tools.
     */
    public int hashCode() {
        int result = 17;

        result = 37 * result
                + (getUserId() == null ? 0 : this.getUserId().hashCode());
        result = 37
                * result
                + (getContextVarTypeId() == null ? 0 : this
                        .getContextVarTypeId().hashCode());
        return result;
    }
}